#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr 12 09:05:00 2025

@author: martin
"""

import os
import pandas as pd
import streamlit as st
from ui_funcs import combine_data, extract_from_screenshots, offline_analysis

if os.path.exists('data.csv'):
    df = pd.read_csv('data.csv')
    top_ds = 'Offline' in df.columns
else:
    df = None
    top_ds = None

loader, analysis = st.tabs(['Process Screenshots', 'Analyse Single Club data'])

with loader:
    st.text(
        """
        It's recommended to upload screenshots from one club at a time.
        
        You can also upload multiple data files generated by this app to
        combine into one big file for later analysis.
        """
    )
    combine_data('Toptracer')
    combine_data('Trackman')
    extract_from_screenshots('Toptracer')
    extract_from_screenshots('Trackman')


with analysis:
    if df is None:
        st.text(
            """
            No dataset in memory. Please upload 
            screenshots or a data file to proceed"""
        )
    else:
        st.text('Detected uploaded data')
        club_options = df['Club'].unique()
        if club_options.size == 1:
            club = club_options[0]
            st.text(f'Only detected one club in dataset: {club}')
        else:
            club = st.selectbox('Select a club', club_options)
        offline_analysis(df, top_ds, club)

    # graph of distance vs side, vertical patches for side (good, ok, bad)
    # also show percentages for above

    # ball speed and launch angle
    # combo of these should give distance but other factors may impact it
